pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Complete') {
            steps {
                echo "Job Completed"
            }
        }
    }
}
